[tool.ruff]
target-version = "py312"

line-length = 120

fix = true

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    # pydocstyle, explicitly not turned on because I have no standards xD
    "D",

    # flake8-todos, flake8-fixme, etc are all disabled because I want to keep todos around for now
    "TD",
    "FIX",

    "E501", # Line too long

    "A003", # Class attribute shadowing a bulitin; doesn't have the same issue as variables or arguments since its namespaced by the object.
]

[tool.ruff.lint.per-file-ignores]
"*_test.py" = ["ANN201", "S101"]

[tool.ruff.lint.isort]
force-wrap-aliases = true
combine-as-imports = true
force-sort-within-sections = true
